In [1]:
import numpy as np

# Ein Vektor ist in Numpy für den Anfang ein 1D-Array. Bei exakten komplexeren Rechnungen ist es besser, die passenden Spalten- und Zeilen-Arrays zu nutzen
v = np.array([3, 5])
w = np.array([2, -1])
print("v = ", v)
print("w = ", w)

# Vektoren addieren
print("v + w = ", v + w)
# Skalarmultiplikatiion - Vektorstreckung, -strauchung
print("2 *v = ", 2 * v)

v =  [3 5]
w =  [ 2 -1]
v + w =  [5 4]
2 *v =  [ 6 10]


In [3]:
# Standardbasisvektoren in 2D
i_hat = np.array([1, 0])  # X-Achse
j_hat = np.array([0, 1])  # y-Achse
# Jeder Vektor ist eine Linear Kombination von i_hat und j_hat
a, b = 3, 5
v_rekonstruiert = a * i_hat + b * j_hat
print("Rekonstruiert: ", v_rekonstruiert)
# Lineare Abhängigkeit prüfen
M = np.array([[1, 2], [2, 4]]) # zweite Zeile ist erste Zeile *2 ==> Linear abhängig
if np.linalg.matrix_rank(M) == 1:
    print("Linear abhängig = Span ist eine Linie durch den Ursprung")
else: 
    print("Linear unabhängig = Span(R^2)")

Rekonstruiert:  [3 5]
Linear abhängig = Span ist eine Linie durch den Ursprung


In [4]:
# Matrix = Transformation des Raums
# Spalten der Matrix = wohin i_hat und j_hat wandern
# Beispiel 90°-Rotation gegen den Uhrzeigersinn
# i_hat (1, 0) ==> (0, 1)
# j_hat (0, 1) ==> (-1, 0)
A_rotation = np.array([[0,-1], [1, 0]])
v = np.array([3, 1])
v_transformiert = A_rotation @ v
print("Original: ", v)
print("Nach 90° Rotation gegen den Uhrzeigersinn: ", v_transformiert)


Original:  [3 1]
Nach 90° Rotation gegen den Uhrzeigersinn:  [-1  3]


In [7]:
# A * B ==> erst B (Spiegelung X-Achse) dann A (90° Rotation gegen)
A_spiegelung = np.array([[1,  0],[0, -1]])
A_rotation = np.array([[0,-1], [1, 0]])
# Erst Rotieren dann Spiegeln
A_rot_dann_spiegel = A_spiegelung @ A_rotation

# Erst Spiegeln dann Rotation
A_spiegel_dann_rot = A_rotation @ A_spiegelung
V = np.array([1, 0])
print("Rot dann Spiegel:", A_rot_dann_spiegel @ v)
print("Spiegel dann Rot:", A_spiegel_dann_rot @ v)
if np.allclose(A_rot_dann_spiegel @ v, A_spiegel_dann_rot @ v):
    print("Die Reihenfolge ist nicht wichtig")
else:
    print("Die Reihenfolge ist absolut entscheidend und wichtig")


Rot dann Spiegel: [-1 -3]
Spiegel dann Rot: [1 3]
Die Reihenfolge ist absolut entscheidend und wichtig


In [ ]:
# A x B = erst B anwenden, dann A (Matrixkomposition)

#Spiegelung an der x-Achse (y-Koordinate negieren)
A_spiegelung = np.array([[1, 0], [0, -1]])

# Rotation um 90°
A_rotation = np.array([[0, -1], [1, 0]])

# Erst rotieren, dann spiegeln
A_rot_dann_spiegel = A_spiegelung @ A_rotation

# Erst spiegeln, dann rotieren
A_spiegel_dann_rot = A_rotation @ A_spiegelung

V = np.array([1, 0])
print("Rotation dann Spiegelung: ", A_rot_dann_spiegel @ v)
print("Spiegelung dann Rotation: ", A_spiegel_dann_rot @ v)
print("Sind sie gleich? ", np.allclose(A_rot_dann_spiegel @ v, A_spiegel_dann_rot @ v))
# Die Ausgabe beweist, dass die Reihenfolge absolut wichtig ist AxB ≠ BxA

Rotation dann Spiegelung:  [-1 -3]
Spiegelung dann Rotation:  [1 3]
Sind sie gleich?  False


In [10]:
# Nützliche Operationen, die im Lernplan immer wieder vorkommen

# Tansponieren (Zeilen und Spalten tauschen)
A = np.array([[1, 2, 3], 
              [4, 5, 6]])
print("Original (2x3): \n", A)
print("Transponiert (3x2): \n", A.T)

# Skalarpordukt (Dot Product)
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])
print("Skalarprodukt v . W: ", np.dot(v, w)) # 1 * 4 + 2 * 5 + 3 * 6 = 32

# Norm (Länge) eines Vektors
print("Länge von v: ", np.linalg.norm(v)) # sqrt(1² + 2² + 3²) = ~3.742

# Einheitsvektor normiert
v_norm = v / np.linalg.norm(v)
print("Einheitsvektor: ", v_norm)
print("Länge des Einheitsvektors: ", np.linalg.norm(v_norm)) # Erwartet: 1.0

Original (2x3): 
 [[1 2 3]
 [4 5 6]]
Transponiert (3x2): 
 [[1 4]
 [2 5]
 [3 6]]
Skalarprodukt v . W:  32
Länge von v:  3.7416573867739413
Einheitsvektor:  [0.26726124 0.53452248 0.80178373]
Länge des Einheitsvektors:  1.0


In [3]:
# Eigenvektoren und Eigenwerte - heute nur anschauen, nicht auswendig lernen
# Kommen in W2 (3B1B Videos 13 -16) ausführlich

A = np.array([[3, 1], 
              [0, 2]])

eigenwerte, eigenvektoren = np.linalg.eig(A)
print("Eigenwerte: ", eigenwerte)
print("Eigenvektoren (Spalten): \n", eigenvektoren)

# Bedeutung: Für jeden Eigenvektor v gilt: A @ v = lambda * v
# Die Matrix streckt/staucht diesen Vektor, dreht ihn aber nicht.
lambdal = eigenwerte[0]
evl = eigenvektoren[:, 0]
print("Probe: A @ evl = ", A @ evl)
print("lambdal * evl = ", lambdal * evl)
print("Gleich?", np.allclose(A @ evl, lambdal * evl))

Eigenwerte:  [3. 2.]
Eigenvektoren (Spalten): 
 [[ 1.         -0.70710678]
 [ 0.          0.70710678]]
Probe: A @ evl =  [3. 0.]
lambdal * evl =  [3. 0.]
Gleich? True
