In [ ]:
# Import und Verifikation
import numpy as np
print('NumPy Version: ', np.__version__)

#Vergleich Python-Liste vs. Numpy-Array
python_liste = [1, 2, 3, 4, 5]
numpy_array = np.array([1, 2, 3, 4, 5])

# Vektoroperationen -- der Kernvorteil
print(python_liste * 2)
print(numpy_array * 2)
print(numpy_array ** 2)
print(numpy_array.mean())
print(numpy_array.std())

NumPy Version:  2.4.3
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
[ 1  4  9 16 25]
3.0
1.4142135623730951


In [ ]:
# Array-Erstellung
# Verschiedene Erstellungsmethoden
nullen = np.zeros((3,4)) # 3x4 Matrix mit Nullen
einsen = np.ones((2,3)) # 2x3 Matrix mit Einsen
identität = np.eye(4) # 4x4 Einheitsmatrix
zufall = np.random.randn(3,3) # normalverteilte Zufallswerte

# Sequenzen
linspace = np.linspace(0, 1, 11) # 11 gleichmäßige Punkte [0, 0.1, ..., 1.0]
arange = np.arange(0, 10, 2) # [0, 2, 4, 6, 8]
print('Einheitsmatrix: ')
print(identität)
print('Shape: ', identität.shape) # (4, 4)
print('Dtype: ', identität.dtype) # float64

Einheitsmatrix: 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Shape:  (4, 4)
Dtype:  float64


In [ ]:
# Indexing und Slicing
# 2D-Array erstellen
A = np.array([[1, 2, 3], 
            [4, 5, 6], 
            [7, 8, 9]])
print(A[0, 0]) # 1 -- erste Zeile, erste Spalte
print(A[1, :]) # [4,5,6] -- gesamte zweite Zeile
print(A[:, 0]) # [1,4,7] -- gesamte erste Spalte
print(A[0:2, 1:]) # [[2,3], [5,6]] -- Submatrix (2x2)

# Boolean Indexing -- wird in scikit-learn ständig gebraucht
werte = np.array([10, 25, 8, 42, 15, 33])
maske = werte > 20
print(maske) # [F, T, F, T, F, T]
print(werte[maske]) # [25, 42, 33] Kurzform
print(werte[werte>20]) # identisch mit Vorzeile


1
[4 5 6]
[1 4 7]
[[2 3]
 [5 6]]
[False  True False  True False  True]
[25 42 33]
[25 42 33]


In [2]:
name = input('>>')
print(name)

Alp
