In [2]:
import numpy as np

X = np.array([[0.5, 1.5], [1, 1], [1.5, 0.5],
              [3, 0.5], [2, 2], [1, 2.5]])   # 6 Beispiele, 2 Merkmale
y = np.array([0, 0, 0, 1, 1, 1])
w = np.array([1.0, 1.0])
b = -3.0


def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def kosten_logistisch(X, y, w, b):
    z = X @ w + b
    p = sigmoid(z)
    loss = -y * np.log(p) - (1-y) * np.log(1-p)
    total_loss = np.mean(loss)
    return z, loss, total_loss

z, loss, total_loss = kosten_logistisch(X, y, w, b)
print(z)
print(loss)
print(total_loss)

#[-2.  -2.  -2.  -0.5  0.  -0.5]
#[0.12692801 0.12692801 0.12692801 0.97407698 0.69314718 0.97407698]
#0.5036808636748461

[-1.  -1.  -1.   0.5  1.   0.5]
[0.31326169 0.31326169 0.31326169 0.47407698 0.31326169 0.47407698]
0.36686678640551745
