In [2]:
import numpy as np
np.set_printoptions(precision=4, suppress=True)

D  = np.array([[2, 8], [8, 9], [8, 13]], dtype=float)
n  = D.shape[0]                       # 3 Zeilen
X  = D - D.mean(axis=0)               # zentriert       (Schritt 3)
Xs = X / D.std(axis=0, ddof=1)        # standardisiert  (Schritt 4)
C  = X.T @ X / (n-1)                  # Kovarianzmatrix (Schritt 5)

print(Xs)

[[-1.1547 -0.7559]
 [ 0.5774 -0.378 ]
 [ 0.5774  1.1339]]


In [3]:
lams, vecs = np.linalg.eigh(C)
lams    # [ 3. 16.]
vecs    # [[ 0.5547 -0.8321]
        #  [-0.8321 -0.5547]]

array([[ 0.5547, -0.8321],
       [-0.8321, -0.5547]])

In [4]:
print(C @ vecs[:, 1])     # [-13.3128  -8.8752]
print(16 * vecs[:, 1])    # [-13.3128  -8.8752]

[-13.3128  -8.8752]
[-13.3128  -8.8752]


In [5]:
S = Xs.T @ Xs / (n-1)
S

array([[1.    , 0.6547],
       [0.6547, 1.    ]])

In [6]:
lams, vecs = np.linalg.eigh(S)
lams_switch = lams[::-1]
vecs_switch = vecs[:, ::-1]
print(lams_switch)
print(vecs_switch)

[1.6547 0.3453]
[[-0.7071  0.7071]
 [-0.7071 -0.7071]]


In [7]:
scores = Xs @ vecs_switch
print(scores)

[[ 1.351  -0.282 ]
 [-0.141   0.6755]
 [-1.21   -0.3935]]


In [8]:
anteile = lams_switch * 100 / lams_switch.sum()
print(anteile)

[82.7327 17.2673]


In [9]:
import numpy as np

A = np.array([[1., 1.],
              [1., 2.],
              [1., 3.]])
y = np.array([1., 2., 2.])

Q, R = np.linalg.qr(A)
print("R =\n", R.round(3))            # obere Dreiecksmatrix
print("QᵀQ =\n", (Q.T @ Q).round(10)) # Einheitsmatrix → Qᵀ ersetzt die Inverse

z = Q.T @ y                           # rechte Seite von R·w = Qᵀy

# Rückwärtseinsetzen: unterste Zeile zuerst
w = z[1] / R[1, 1]
b = (z[0] - R[0, 1] * w) / R[0, 0]
print("b =", round(b, 4), " w =", round(w, 4))

R =
 [[-1.732 -3.464]
 [ 0.    -1.414]]
QᵀQ =
 [[ 1. -0.]
 [-0.  1.]]
b = 0.6667  w = 0.5


In [10]:
print(np.linalg.cond(A))          # 6.79
print(np.linalg.cond(A.T @ A))    # 46.14  = 6.79²

6.793010808505649
46.14499584447445
