In [21]:
import numpy as np
np.set_printoptions(precision=4, suppress=True)

D  = np.array([[2, 8], [8, 9], [8, 13]], dtype=float)
n  = D.shape[0]                       # 3 Zeilen
X  = D - D.mean(axis=0)               # zentriert       (Schritt 3)
Xs = X / D.std(axis=0, ddof=1)        # standardisiert  (Schritt 4)
C  = X.T @ X / (n-1)                  # Kovarianzmatrix (Schritt 5)

print(Xs)

[[-1.1547 -0.7559]
 [ 0.5774 -0.378 ]
 [ 0.5774  1.1339]]


In [19]:
lams, vecs = np.linalg.eigh(C)
lams    # [ 3. 16.]
vecs    # [[ 0.5547 -0.8321]
        #  [-0.8321 -0.5547]]

array([[ 0.5547, -0.8321],
       [-0.8321, -0.5547]])

In [20]:
print(C @ vecs[:, 1])     # [-13.3128  -8.8752]
print(16 * vecs[:, 1])    # [-13.3128  -8.8752]

[-13.3128  -8.8752]
[-13.3128  -8.8752]


In [24]:
S = Xs.T @ Xs / (n-1)
S

array([[1.    , 0.6547],
       [0.6547, 1.    ]])

In [28]:
lams, vecs = np.linalg.eigh(S)
lams_switch = lams[::-1]
vecs_switch = vecs[:, ::-1]
print(lams_switch)
print(vecs_switch)

[1.6547 0.3453]
[[-0.7071  0.7071]
 [-0.7071 -0.7071]]


In [29]:
scores = Xs @ vecs_switch
print(scores)

[[ 1.351  -0.282 ]
 [-0.141   0.6755]
 [-1.21   -0.3935]]


In [33]:
anteile = lams_switch * 100 / lams_switch.sum()
print(anteile)

[82.7327 17.2673]
