In [1]:
import numpy as np


def erweitere_merkmale(x, grad):
    X = np.column_stack([x**i for i in range(1, grad + 1)])
    return X

X_poly = erweitere_merkmale(np.array([1, 2, 3]), 3)
print(X_poly)


[[ 1  1  1]
 [ 2  4  8]
 [ 3  9 27]]
