In [1]:
import numpy as np

# Spalte 0: Einkommen (Tsd. €), Spalte 1: Verschuldungsquote (%)
X = np.array([[62, 25],
              [38, 48],
              [55, 30],
              [29, 55],
              [71, 20],
              [44, 42],
              [33, 50],
              [58, 35]], dtype=float)

y = np.array([0, 1, 0, 1, 0, 1, 1, 0])   # 1 = Ausfall


kandidaten = [
    (np.array([ 1.0, -1.0]), 0.0),   # Modell A
    (np.array([-1.0,  1.0]), 0.0),   # Modell B
    (np.array([-2.0,  2.0]), 0.5),   # Modell C
]



def standardisiere(X):
    mu = np.mean(X, axis=0)
    sigma = np.std(X, axis=0)
    X_std = (X - mu) / sigma
    return mu, sigma, X_std

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def kosten_logistisch(X, y, w, b):
    z = X @ w + b
    p = sigmoid(z)
    loss = -y * np.log(p) - (1-y) * np.log(1-p)
    cost = np.mean(loss)
    return cost

def vorhersage(X, w, b):
    z = X @ w + b
    y_hat = (z >= 0).astype(int)
    #prediction = [1 if zi >= 0 else 0 for zi in z] ist eine Liste, daher die andere Form, die einen Array liefert und auch kürzer und einfacher ist.
    return y_hat

def genauigkeit(y, y_hat):
    return (y == y_hat).mean()

mu, sigma, X_std = standardisiere(X)
cost_modelle = []
y_hats = []
anteile = []
for w, b in kandidaten:
    #cost_per_modell = kosten_logistisch(X_std, y, w, b)
    cost_modelle.append(kosten_logistisch(X_std, y, w, b))
    y_hat = vorhersage(X_std, w, b)
    y_hats.append(y_hat)
    #anteil = genauigkeit(y, y_hat)
    anteile.append(genauigkeit(y, y_hat))

cost_modelle = np.array(cost_modelle)
y_hats = np.array(y_hats)
anteile = np.array(anteile)

for cost in cost_modelle:
    print(f"{cost:.4f}")
print(y)
for y_hat in y_hats:
    print(y_hat)

for anteil in anteile:
    print(f"{anteil:.4f}")

2.0026
0.1929
0.0751
[0 1 0 1 0 1 1 0]
[1 0 1 0 1 0 0 1]
[0 1 0 1 0 1 1 0]
[0 1 0 1 0 1 1 0]
0.0000
1.0000
1.0000
